const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const COMB = path.join(ROOT, "조합");
const EFF = path.join(ROOT, "효과");
const GRADES = ["희귀", "영웅", "전설", "신화"];
const RELICS = [
  ["초월", "초월의성물"],
  ["외형", "외형의성물"],
  ["황금", "황금의성물"],
  ["경험", "경험의성물"],
];

function read(p) {
  return fs.readFileSync(p, "utf8").replace(/^\uFEFF/, "");
}

function parseHanjang(file, grade) {
  const text = read(file);
  const cards = [];
  const lines = text.split(/\r?\n/);
  let pending = null;
  const flush = () => {
    if (pending) {
      cards.push(pending);
      pending = null;
    }
  };
  for (const raw of lines) {
    const line = raw.trim();
    let m = line.match(/^(\d+)\.\s+\+\d+p\s+\/\s+(.+)$/);
    if (!m) m = line.match(/^(\d+)\.\s+(.+?)\s+—\s+(초월|무기외형)(.*)$/);
    if (m) {
      flush();
      const name = m[2].trim().replace(/\s+\(.+$/, "");
      if (m[3]) {
        pending = {
          name,
          kind: m[3] === "무기외형" ? "무기외형" : "초월",
          grade,
        };
      } else {
        pending = { name, kind: "초월", grade };
      }
      continue;
    }
    if (pending) {
      // JS \b는 한글에서 경계로 안 잡혀서 (?:\s|/|$) 사용
      const k = line.match(/^종류:\s*(초월|무기외형)(?:\s|\/|$)/);
      if (k) pending.kind = k[1];
    }
  }
  flush();
  return cards;
}

function parsePairs(file, grade) {
  const text = read(file);
  const pairs = [];
  const chunks = text.split(/-{10,}/);
  for (const chunk of chunks) {
    const head = chunk.match(/페어\s+(\d+)\s+—\s+(\d+)장[^\n]*/);
    if (!head) continue;
    const size = Number(head[2]);
    const enh = (chunk.match(/전부\s+(\d)강/) || [])[1];
    const cards = [];
    for (const line of chunk.split(/\r?\n/)) {
      const m = line.trim().match(/^[-·]\s+(.+?)\s+(\d)강\s*$/);
      if (m) cards.push(m[1].trim());
    }
    if (!cards.length) continue;
    pairs.push({
      id: Number(head[1]),
      grade,
      size,
      enhance: Number(enh || 1),
      cards,
    });
  }
  return pairs;
}

function parseEffects(dir) {
  const out = {};
  for (const g of GRADES) {
    const text = read(path.join(dir, g + ".txt"));
    out[g] = [];
    for (const line of text.split(/\r?\n/)) {
      const m = line.match(/^(\d{1,3})\s{2,}(.+)$/);
      if (m) out[g].push({ at: Number(m[1]), text: m[2].trim() });
    }
  }
  return out;
}

function parseTiers(dir) {
  const file = path.join(dir, "티어.txt");
  if (!fs.existsSync(file)) return null;
  const out = { PVE: [], PVP: [] };
  let mode = null;
  for (const raw of read(file).split(/\r?\n/)) {
    const line = raw.trim();
    if (line === "PVE" || line === "PVP") {
      mode = line;
      continue;
    }
    const m = line.match(/^(\d+)티어\s+(.+)$/);
    if (mode && m) out[mode].push({ tier: Number(m[1]), stat: m[2].trim() });
  }
  return out;
}

const hanjang = {};
for (const g of GRADES) {
  const file = path.join(COMB, "초월의성물", g + ".txt");
  hanjang[g] = parseHanjang(file, g);
}

const relics = {};
for (const [key, folder] of RELICS) {
  relics[key] = { pairs: {} };
  for (const g of GRADES) {
    relics[key].pairs[g] = parsePairs(
      path.join(COMB, folder, g + "-페어.txt"),
      g
    );
  }
}

const effects = {};
const tiers = {};
for (const [key, folder] of RELICS) {
  const dir = path.join(EFF, folder);
  effects[key] = parseEffects(dir);
  const t = parseTiers(dir);
  if (t) tiers[key] = t;
}

const names = new Set();
for (const g of GRADES) for (const c of hanjang[g]) names.add(c.name);
const missing = [];
for (const [key] of RELICS) {
  for (const g of GRADES) {
    for (const p of relics[key].pairs[g]) {
      for (const n of p.cards) {
        if (!names.has(n)) missing.push(key + " " + g + " " + n);
      }
    }
  }
}
const summary = {
  hanjang: Object.fromEntries(GRADES.map((g) => [g, hanjang[g].length])),
  pairs: Object.fromEntries(
    RELICS.map(([k]) => [
      k,
      Object.fromEntries(GRADES.map((g) => [g, relics[k].pairs[g].length])),
    ])
  ),
  missing,
};

const js =
  "/* generated by _build-data.js */\nwindow.BIND_DATA = " +
  JSON.stringify({ grades: GRADES, hanjang, relics, effects, tiers }, null, 2) +
  ";\n";

fs.writeFileSync(path.join(ROOT, "data.js"), js, "utf8");
console.log(JSON.stringify(summary, null, 2));
